[Password]

                                                Keystore = 'lvc_svc_task_pgres'

                                                [Database]

                                                URL = 'postgresql://postgres:lvc_svc_task_pgres@cl-postgres:5432/postgres?sslmode=disable'

                                                
